# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 06:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=200)),
                ('year', models.DateField()),
                ('pages', models.IntegerField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('pack', models.CharField(max_length=50)),
                ('ISBN', models.FloatField(max_length=100)),
                ('jj', models.CharField(max_length=1000)),
                ('tt', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiuid', models.IntegerField(max_length=50)),
                ('shouusername', models.CharField(max_length=50)),
                ('shoulocation', models.CharField(max_length=500)),
                ('liuyan', models.CharField(max_length=1000)),
                ('phone', models.IntegerField(max_length=50)),
                ('ISBN', models.FloatField(max_length=50)),
                ('bookname', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('tt', models.CharField(max_length=100)),
                ('songid', models.IntegerField(max_length=50)),
                ('listid', models.IntegerField(max_length=50)),
                ('songusername', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0, max_length=10)),
                ('datatime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('sendnumber', models.IntegerField(default=0, max_length=50)),
                ('obtainnumber', models.IntegerField(default=0, max_length=50)),
                ('fishbean', models.CharField(default=0, max_length=50)),
                ('usertype', models.IntegerField(default=0, max_length=10)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
