# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fishbean',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='obtainnumber',
            field=models.IntegerField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='sendnumber',
            field=models.IntegerField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
    ]
